# Generated by Django 6.0.6 on 2026-07-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default=1999, verbose_name='价格'),
            preserve_default=False,
        ),
    ]
