# Generated by Django 6.0.6 on 2026-09-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_alter_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detail',
            field=models.TextField(blank=True, verbose_name='详细说明'),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '项目报价'), (2, '合同变更'), (3, '设计变更'), (4, '收款/开票'), (5, '其他商务事项')], default=5, verbose_name='事项类型'),
        ),
        migrations.AlterField(
            model_name='order',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.CharField(max_length=64, unique=True, verbose_name='工单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待处理'), (2, '处理中'), (3, '已完成'), (4, '已驳回')], default=1, verbose_name='处理状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=64, verbose_name='事项名称'),
        ),
        migrations.AlterField(
            model_name='taskmanage',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.employee', verbose_name='执行者'),
        ),
    ]
