# Generated by Django 6.0.6 on 2026-09-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_order_detail_order_type_alter_order_admin_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_admins', to='auth.group', verbose_name='角色组'),
        ),
    ]
