# Generated by Django 6.0.6 on 2026-10-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_admin_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
