# Generated by Django 6.0.6 on 2026-10-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_admin_is_active_alter_admin_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'permissions': [('manage_admin_roles', 'can manage admin roles')]},
        ),
    ]
