# Generated by Django 6.0.6 on 2026-10-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_admin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'permissions': [('manage_admin_roles', 'can manage admin roles'), ('reset_admin_password', 'can reset admin password')]},
        ),
    ]
