# Generated by Django 6.0.6 on 2026-10-07 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_alter_admin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_info', to='app01.admin', verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='app01.department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='position',
            field=models.CharField(blank=True, max_length=32, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='signatuer',
            field=models.CharField(blank=True, max_length=128, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='avatar',
            field=models.CharField(blank=True, max_length=128, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='email',
            field=models.CharField(blank=True, max_length=64, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
    ]
