# Generated by Django 6.0.6 on 2026-10-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_profileinfo_admin_profileinfo_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='signatuer',
            new_name='signature',
        ),
    ]
