# Generated by Django 6.0.6 on 2026-10-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_rename_signatuer_profileinfo_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='年龄'),
        ),
    ]
