# Generated by Django 6.0.6 on 2026-10-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_profileinfo_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
    ]
