# Generated by Django 6.0.6 on 2026-10-09 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0017_alter_profileinfo_age_alter_profileinfo_email"),
    ]

    operations = [
        # 1. 重命名员工部门字段，保留原有数据
        migrations.RenameField(
            model_name="employee",
            old_name="depart",
            new_name="department",
        ),
        # 2. 重命名员工入职时间字段，保留原有数据
        migrations.RenameField(
            model_name="employee",
            old_name="entrytime",
            new_name="entry_date",
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="app01.department",
                verbose_name="所属部门",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="entry_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="入职时间",
            ),
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="职位名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="说明"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="app01.department",
                verbose_name="上级部门",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_no",
            field=models.CharField(
                blank=True, max_length=32, null=True, unique=True, verbose_name="工号"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="年龄"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.SmallIntegerField(
                blank=True,
                choices=[(1, "男"), (2, "女")],
                null=True,
                verbose_name="性别",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=32, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="password",
            field=models.CharField(max_length=128, verbose_name="旧密码字段"),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="app01.position",
                verbose_name="职位",
            ),
        ),
    ]
