# Generated by Django 6.0.6 on 2026-10-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_position_department_is_active_department_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
