# Generated by Django 6.0.6 on 2026-10-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_position_remove_employee_depart_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='account',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('email_verified', models.BooleanField(default=False, verbose_name='邮箱已验证')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='手机已验证')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_account', to='app01.employee', verbose_name='关联员工')),
                ('groups', models.ManyToManyField(blank=True, related_name='accounts', to='auth.group', verbose_name='角色组')),
            ],
            options={
                'permissions': [('manage_account_roles', 'can manage account roles'), ('reset_account_password', 'can reset account password')],
            },
        ),
    ]
