# Generated by Django 6.0.6 on 2026-10-09 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_remove_employee_depart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='depart',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app01.department', verbose_name='所属部门'),
        ),
    ]
